# Generated by Django 5.2.4 on 2025-07-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='commuterprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
